
# see docs at https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - 'dependabot:robot:'
    ignore:
    # Ignored because the csproj using this supports 2 different target frameworks and dependabot
    # does not know that for target framework netcoreapp3.1 the Microsoft.AspNetCore.Mvc.Testing
    # nuget cannot be higher than 3.x.x
    # This NuGet needs to be manually updated for the other target framework
    - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "weekly"
    labels:
    - 'dependabot:robot:'
