
# see docs at https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - 'dependabot'
      - 'bot:robot:'
      - 'nuget'
    ignore:
      # Ignored because the csproj using this  NuGet supports multiple target frameworks and dependabot does not handle this well.
      # This NuGet needs to be manually updated for each target framework
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: "daily"
    labels:
      - 'dependabot'
      - 'bot:robot:'
      - 'github-workflows'
  - package-ecosystem: github-actions
    directory: '.github/actions/create-gh-status'
    schedule:
      interval: "daily"
    labels:
      - 'dependabot'
      - 'bot:robot:'
      - 'github-custom-action'
  - package-ecosystem: github-actions
    directory: '.github/actions/create-nuget-release-flow-info-artifact'
    schedule:
      interval: "daily"
    labels:
      - 'dependabot'
      - 'bot:robot:'
      - 'github-custom-action'
  - package-ecosystem: github-actions
    directory: '.github/actions/read-nuget-release-flow-info-artifact'
    schedule:
      interval: "daily"
    labels:
      - 'dependabot'
      - 'bot:robot:'
      - 'github-custom-action'

