# Why was this action created:
#
# This is used to read the artifact with information required to update the NuGet release flow
# diagram in the NuGet release issue.
#

name: 'Read NuGet release flow info artifact'
description: 'Uploads an artifact with information to update the NuGet release flow diagram'

inputs:
  workflow-id:
    description: 'The id of the workflow that contains the NuGet release flow info artifact.'
    required: true
  workflow-run-id:
    description: 'The id of the workflow run that contains the NuGet release flow info artifact.'
    required: true

outputs:
  issue-number:
    description: 'The number of the issue for the NuGet release.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-number }}
  nuget-id:
    description: 'The NuGet ID.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-id }}
  nuget-version:
    description: 'The NuGet version.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-version }}
  nuget-release-status:
    description: 'The status of the NuGet release flow.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-status }}
  nuget-release-badge-color:
    description: 'The color to use for the badge on the NuGet release flow.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-badge-color }}
  issue-nuget-release-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release GitHub issue action.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-nuget-release-node-status }}
  issue-nuget-release-url:
    description: 'The URL for the NuGet release GitHub issue action.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-nuget-release-url }}
  nuget-release-command-handler-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release command handler action.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-command-handler-node-status }}
  nuget-release-command-handler-url:
    description: 'The URL for the NuGet release command handler action.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-command-handler-url }}
  nuget-release-pull-request-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release pull request.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-pull-request-node-status }}
  nuget-release-pull-request-url:
    description: 'The URL for the NuGet release pull request.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-pull-request-url }}
  publish-nuget-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release publish action.'
    value: ${{ steps.nuget-release-flow-info.outputs.publish-nuget-node-status }}
  publish-nuget-url:
    description: 'The URL for the NuGet release publish action.'
    value: ${{ steps.nuget-release-flow-info.outputs.publish-nuget-url }}

runs:
  using: "composite"
  steps:
  - name: Download NuGet release flow info artifact
    uses: dawidd6/action-download-artifact@v2.17.0
    with:
      workflow: ${{ inputs.workflow-id }}
      name:  nuget-release-flow-info
      run_id: ${{ inputs.workflow-run-id }}
  - name: Read NuGet release flow info artifact
    id: nuget-release-flow-info
    shell: pwsh
    run: |
      $releaseFlowInfo = Get-Content ./nuget-release-flow-info.md | ConvertFrom-Json
      Write-Host "::set-output name=issue-number::$($releaseFlowInfo.issueNumber)"
      Write-Host "::set-output name=nuget-id::$($releaseFlowInfo.nugetId)"
      Write-Host "::set-output name=nuget-version::$($releaseFlowInfo.nugetVersion)"
      Write-Host "::set-output name=nuget-release-status::$($releaseFlowInfo.nugetReleaseStatus)"
      Write-Host "::set-output name=nuget-release-badge-color::$($releaseFlowInfo.nugetReleaseBadgeColor)"
      Write-Host "::set-output name=issue-nuget-release-node-status::$($releaseFlowInfo.issueNugetReleaseNodeStatus)"
      Write-Host "::set-output name=issue-nuget-release-url::$($releaseFlowInfo.issueNugetReleaseUrl)"
      Write-Host "::set-output name=nuget-release-command-handler-node-status::$($releaseFlowInfo.nugetReleaseCommandHandlerNodeStatus)"
      Write-Host "::set-output name=nuget-release-command-handler-url::$($releaseFlowInfo.nugetReleaseCommandHandlerUrl)"
      Write-Host "::set-output name=nuget-release-pull-request-node-status::$($releaseFlowInfo.nugetReleasePullRequestNodeStatus)"
      Write-Host "::set-output name=nuget-release-pull-request-url::$($releaseFlowInfo.nugetReleasePullRequestUrl)"
      Write-Host "::set-output name=publish-nuget-node-status::$($releaseFlowInfo.publishNugetNodeStatus)"
      Write-Host "::set-output name=publish-nuget-url::$($releaseFlowInfo.publishNugetUrl)"
  - name: Dump outputs from previous step
    shell: pwsh
    env:
      STEP_OUTPUT: ${{ toJSON(steps.nuget-release-flow-info.outputs) }}
    run: $env:STEP_OUTPUT
