# Why was this action created:
#
# This is used to read the artifact with information required to update the NuGet release flow
# diagram in the NuGet release issue.
#

name: 'Read NuGet release flow info artifact'
description: 'Uploads an artifact with information to update the NuGet release flow diagram'

inputs:
  workflow-id:
    description: 'The id of the workflow that contains the NuGet release flow info artifact.'
    required: true
  workflow-run-id:
    description: 'The id of the workflow run that contains the NuGet release flow info artifact.'
    required: true

outputs:
  issue-number:
    description: 'The number of the issue for the NuGet release.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-number }}
  nuget-id:
    description: 'The NuGet ID.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-id }}
  nuget-version:
    description: 'The NuGet version.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-version }}
  nuget-release-status:
    description: 'The status of the NuGet release flow.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-status }}
  nuget-release-badge-color:
    description: 'The color to use for the badge on the NuGet release flow.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-badge-color }}
  issue-nuget-release-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release GitHub issue action.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-nuget-release-node-status }}
  issue-nuget-release-url:
    description: 'The URL for the NuGet release GitHub issue action.'
    value: ${{ steps.nuget-release-flow-info.outputs.issue-nuget-release-url }}
  nuget-release-command-handler-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release command handler action.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-command-handler-node-status }}
  nuget-release-command-handler-url:
    description: 'The URL for the NuGet release command handler action.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-command-handler-url }}
  nuget-release-pull-request-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release pull request.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-pull-request-node-status }}
  nuget-release-pull-request-url:
    description: 'The URL for the NuGet release pull request.'
    value: ${{ steps.nuget-release-flow-info.outputs.nuget-release-pull-request-url }}
  publish-nuget-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release publish action.'
    value: ${{ steps.nuget-release-flow-info.outputs.publish-nuget-node-status }}
  publish-nuget-url:
    description: 'The URL for the NuGet release publish action.'
    value: ${{ steps.nuget-release-flow-info.outputs.publish-nuget-url }}

runs:
  using: "composite"
  steps:
  - name: Read NuGet release flow info data
    id: nuget-release-flow-info
    uses: edumserrano/share-jobs-data@v1
    with:
      command: read-data-different-workflow
      artifact-name: nuget-release-flow-info
      data-filename: nuget-release-flow-info.json
      run-id: ${{ inputs.workflow-run-id }}
      output: github-step-json
  - name: Dump outputs from previous step
    shell: pwsh
    env:
      STEP_OUTPUT: ${{ toJSON(steps.nuget-release-flow-info.outputs) }}
    run: $env:STEP_OUTPUT
