# Why was this action created:
#
# This is used to create the artifact with information required to update the NuGet release flow
# diagram in the NuGet release issue.
#

name: 'Upload NuGet release flow info artifact'
description: 'Uploads an artifact with information to update the NuGet release flow diagram'
inputs:
  issue-number:
    description: 'The number of the issue for the NuGet release.'
    required: true
  nuget-id:
    description: 'The NuGet ID.'
    required: false
  nuget-version:
    description: 'The NuGet version.'
    required: false
  nuget-release-status:
    description: 'The status of the NuGet release flow.'
    required: true
  nuget-release-badge-color:
    description: 'The color to use for the badge on the NuGet release flow.'
    required: true
  issue-nuget-release-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release GitHub issue action.'
    required: false
  issue-nuget-release-url:
    description: 'The URL for the NuGet release GitHub issue action.'
    required: false
  nuget-release-command-handler-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release command handler action.'
    required: false
  nuget-release-command-handler-url:
    description: 'The URL for the NuGet release command handler action.'
    required: false
  nuget-release-pull-request-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release pull request.'
    required: false
  nuget-release-pull-request-url:
    description: 'The URL for the NuGet release pull request.'
    required: false
  publish-nuget-node-status:
    description: 'The status of the NuGet release flow node for the NuGet release publish action.'
    required: false
  publish-nuget-url:
    description: 'The URL for the NuGet release publish action.'
    required: false

runs:
  using: "composite"
  steps:
  - name: Set NuGet release flow info data
    uses: edumserrano/share-jobs-data@v1
    with:
      command: set-data
      artifact-name: nuget-release-flow-info
      data-filename: nuget-release-flow-info.json
      output: none
      data: |
        issue-number: '${{ inputs.issue-number }}'
        nuget-id: '${{ inputs.nuget-id }}'
        nuget-version: '${{ inputs.nuget-version }}'
        nuget-release-status: '${{ inputs.nuget-release-status }}'
        nuget-release-badge-color: '${{ inputs.nuget-release-badge-color }}'
        issue-nuget-release-node-status: '${{ inputs.issue-nuget-release-node-status }}'
        issue-nuget-release-url: '${{ inputs.issue-nuget-release-url }}'
        nuget-release-command-handler-node-status: '${{ inputs.nuget-release-command-handler-node-status }}'
        nuget-release-command-handler-url: '${{ inputs.nuget-release-command-handler-url }}'
        nuget-release-pull-request-node-status: '${{ inputs.nuget-release-pull-request-node-status }}'
        nuget-release-pull-request-url: '${{ inputs.nuget-release-pull-request-url }}'
        publish-nuget-node-status: '${{ inputs.publish-nuget-node-status }}'
        publish-nuget-url: '${{ inputs.publish-nuget-url }}'
