# Why
#
# You can enable debug logging on workflows by following the guidelines at https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
# However if something didn't work as expected in a workflow run you will have to enable the logging and rerun. You won't have the required
# info at the time the workflow failed.
#
# This action outputs all the known contexts to make it easier to debug when workflows don't work as expected.
# Enabling debug logging might still be required to debug. This is not a replacement for debug logging.
#

name: 'Output contexts'
description: 'Outputs all known contexts. See https://docs.github.com/en/actions/learn-github-actions/contexts.'
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        Write-Host "::group::github context"
        Write-Host '${{ toJson(github) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::env context"
        Write-Host '${{ toJson(env) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::job context"
        Write-Host '${{ toJson(job) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::steps context"
        Write-Host '${{ toJson(steps) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::runner context"
        Write-Host '${{ toJson(runner) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::secrets context"
        Write-Host '${{ toJson(secrets) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::strategy context"
        Write-Host '${{ toJson(strategy) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::matrix context"
        Write-Host '${{ toJson(matrix) }}'
        Write-Host "::endgroup::"

        Write-Host "::group::needs context"
        Write-Host '${{ toJson(needs) }}'
        Write-Host "::endgroup::"
