# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/dispatch-commands-workflow.md

name: Slash command dispatch

on:
  issue_comment:
    types: [created]

jobs:
  main:
    name: Slash command dispatch
    environment: slash-command-dispatch-workflow
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Issue comment command dispatch
      uses: peter-evans/slash-command-dispatch@v2.3.0
      if: github.event.issue.state == 'open'
      with:
        issue-type: issue
        allow-edits: false
        reactions: true
        dispatch-type: repository
        permission: write
        token: ${{ secrets.DISPATCH_COMMANDS_GH_TOKEN }}
        commands: |
          nuget-release
