name: Slash command dispatch

on:
  issue_comment:
    types: [created]

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Slash command dispatch
    environment: slash-command-dispatch-workflow
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - name: Issues - dispatch commands
      uses: peter-evans/slash-command-dispatch@v3
      if: github.event.issue.state == 'open'
      with:
        issue-type: issue
        allow-edits: false
        reactions: true
        dispatch-type: repository
        permission: write
        token: ${{ secrets.DISPATCH_COMMANDS_GH_TOKEN }}
        commands: |
          retry-nuget-release
