# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-dotnet-format-workflow.md

name: dotnet format

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - "**.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
    - "**.md"

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

env:
  STATUS_CONTEXT : ${{ github.workflow }} / dotnet format (${{ github.event_name }}) # mimic format from github checks $workflow-name / $job-name ($event-name)
  WORKFLOW_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}

jobs:
  dotnet-format:
    name: dotnet format
    if: github.event_name == 'pull_request' # missing condition: and if PR is open
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION : 6.0.x
      SLN_FILENAME: DotNet.Sdk.Extensions.sln
      SLN_FILEPATH : ${{ github.workspace }}/DotNet.Sdk.Extensions.sln
      WORKFLOW_INFO_ARTIFACT_FILEPATH: ${{github.workspace}}/workflow-info.json
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Cache/Restore NuGets
      uses: actions/cache@v2
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ env.DOTNET_VERSION }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: dotnet format
      run: |
        dotnet format ${{ env.SLN_FILEPATH }} --severity info --verbosity diagnostic
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Upload repo
      if: steps.changes.outputs.changed == 1
      uses: actions/upload-artifact@v2
      with:
        name: repo
        path: ${{ github.workspace }}
    - name: Log repo artifact info
      run: |
        $hasChanges = [System.Convert]::ToBoolean(steps.changes.outputs.changed)
        if($hasChanges) {
          Write-Host "::notice title=dotnet format::dotnet format detected code guidelines violations  ."
        }
        elseif($pushStepConclusion -eq 'failure') {
          Write-Host "::error title=DotNet.Sdk.Extensions NuGet::Failed to push DotNet.Sdk.Extensions NuGet and symbols."
        }
        elseif($pushStepConclusion -eq 'success') {
          Write-Host "::notice title=DotNet.Sdk.Extensions NuGet::Successfully pushed DotNet.Sdk.Extensions NuGet and symbols to nuget.org. You can find the package at: https://www.nuget.org/packages/DotNet-Sdk-Extensions."
        }
    - name: Save workflow info
      run: |
        $hasChanges = [System.Convert]::ToBoolean(${{ steps.changes.outputs.changed }})
        $body = @{
          hasChanges = $hasChanges
          workflow = "${{ github.workflow }}"
          workflowUrl = "${{ env.WORKFLOW_RUN_URL }}"
          prNumber = "${{ env.PR_NUMBER }}"
          prBranchName = "${{ github.event.client_payload.pull_request.head.ref }}"
        } | ConvertTo-Json
        $body > ${{ env.WORKFLOW_INFO_ARTIFACT_FILEPATH }}
        cat ${{ env.WORKFLOW_INFO_ARTIFACT_FILEPATH }}
    - name: Upload workflow info
      uses: actions/upload-artifact@v2
      with:
        name: workflow-info
        path: ${{ env.WORKFLOW_INFO_ARTIFACT_FILEPATH }}
