name: dotnet format pull requests

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - "**.md"

defaults:
  run:
    shell: pwsh

jobs:
  dotnet-format:
    name: dotnet format
    runs-on: ubuntu-latest
    env:
      SLN_FILEPATH : ${{github.workspace}}/DotNet.Sdk.Extensions.sln
      DOTNET_VERSION : 5.0.303
    steps:
    - name: Debug github event
      run: |
        $githubContext = '${{toJSON(github)}}'
        Write-Host $githubContext
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Install dotnet-format tool
      run:  dotnet tool install --global dotnet-format
    - name: Cache/Restore NuGets
      uses: actions/cache@v2
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{env.DOTNET_VERSION}}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: dotnet format
      run: |
        Write-Host "::group::Running dotnet format"
        dotnet format ${{env.SLN_FILEPATH}} `
          --fix-whitespace `
          --fix-style info `
          --fix-analyzers info `
          --verbosity diagnostic `
          --check
        Write-Host "::endgroup::"
        $hasChanges = $LASTEXITCODE -ne 0
        Write-Host "::set-output name=has-changes::$hasChanges"
        
        if($hasChanges) {
          Write-Host "::warning::dotnet format found files that require formatting."        
        }
        else {
          Write-Host "dotnet format didn't find any file that requires formatting."        
        }

        Exit 0 # always exit successfully
    - name: GitHub PR comment
      run: |
        $prNumber = "${{github.event.pull_request.number}}"
        $prUrl = "https://github.com/edumserrano/dot-net-sdk-extensions/pull/$prNumber"
        # gh pr merge --auto --squash --delete-branch "$prUrl"
        gh auth login
        gh pr comment $prUrl --body "This looks great, lets get it deployed."
