# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-dependabot-auto-merge-workflow.md

name: PR Dependabot auto merge

on:
  workflow_run:
    workflows: ["Publish Nuget packages"]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  auto-merge-pr:
    name: Auto merge dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.workflow_run.head_branch}}
    - name: Approve and merge dependabot PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $prNumber = "${{ github.event.workflow_run.pull_requests[0].number }}"
        gh pr merge --auto --squash --delete-branch $prNumber
