# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-dotnet-format-check-workflow.md

name: PR dotnet format check

on:
  pull_request_target:
    branches: [ main ]
    paths-ignore:
    - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  dotnet-format-check:
    name: PR dotnet format check
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      SLN_FILENAME: DotNet.Sdk.Extensions.sln
      SLN_FILEPATH : ${{ github.workspace }}/DotNet.Sdk.Extensions.sln
      DOTNET_VERSION : 6.0.101
      WORKFLOW_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dotnet-format tool
      run:  dotnet tool install --global dotnet-format
    - name: Cache/Restore NuGets
      uses: actions/cache@v2
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ env.DOTNET_VERSION }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: dotnet format check
      id: dotnet-format
      run: |
        Write-Host "::group::Running dotnet format"
        dotnet format ${{ env.SLN_FILEPATH }} `
          --severity info `
          --verify-no-changes `
          --verbosity diagnostic
        Write-Host "::endgroup::"
        $hasChanges = $LASTEXITCODE -ne 0
        Write-Host "::set-output name=has-changes::$hasChanges"

        if($hasChanges) {
          Write-Host "::error::dotnet format found files that do not respect the code guidelines."
        }
        else {
          Write-Host "::notice::dotnet format didn't find any file that does not respect the code guidelines."
        }
    - name: Setup PR comment
      id: setup-pr-comment
      run: |
        $hasChanges = [System.Convert]::ToBoolean("${{ steps.dotnet-format.outputs.has-changes }}")
        if($hasChanges) {
          Write-Host "::set-output name=pr-comment-template::.github/workflows/templates/pr-dotnet-format-check/dotnet-format-found-changes.md"
        }
        else {
          Write-Host "::set-output name=pr-comment-template::.github/workflows/templates/pr-dotnet-format-check/dotnet-format-did-not-find-changes.md"
        }
    - name: Render comment template
      id: render-pr-comment-template
      uses: chuhlomin/render-template@v1.3
      with:
        template: ${{ steps.setup-pr-comment.outputs.pr-comment-template }}
        vars: |
          workflow: ${{ github.workflow }}
          workflowUrl: ${{ env.WORKFLOW_RUN_URL }}
    - name: Sanitize PR comment
      id: sanitize-pr-comment
      run: |
        $commentBody = "${{ steps.render-pr-comment-template.outputs.result }}"
        $commentBody = $commentBody -replace "`n","%0A" # The content must be escaped to preserve newlines. See https://github.community/t/set-output-truncates-multiline-strings/16852/3
        Write-Host "::set-output name=pr-comment-body::$commentBody"
    - name: Update PR with dotnet format result
      uses: ./.github/actions/create-update-comment
      with:
        issue-number: ${{ env.PR_NUMBER }}
        body-includes: PR dotnet format check
        comment-author: github-actions[bot]
        body: ${{ steps.sanitize-pr-comment.outputs.pr-comment-body }}
        edit-mode: replace
    - name: Set workflow exit status
      run: |
        $hasChanges = [System.Convert]::ToBoolean("${{ steps.dotnet-format.outputs.has-changes }}")
        if($hasChanges) {
          Write-Host "dotnet format found files that do not respect the code guidelines so setting the workflow status as failed."
          Exit 1
        }

        Write-Host "dotnet format didn't find any file that does not respect the code guidelines so setting the workflow status as successful."
        Exit 0
