# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-dependabot-auto-merge-workflow.md

name: PR Dependabot auto merge

on:
  workflow_run:
    workflows: ["Build, test and package"]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
  auto-merge-pr:
    name: Auto merge dependabot PR
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    environment: no-secrets-workflow
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    - name: Approve and merge dependabot PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $prNumber = "${{ github.event.workflow_run.pull_requests[0].number }}"
        gh pr merge --auto --squash --delete-branch $prNumber
