# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-nuget-release-notes-workflow.md

name: PR NuGet release notes

on:
  repository_dispatch:
    types: [nuget-release-notes]
  # pull_request:
  #   branches: [ main ]
  #   types: [ closed ]

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Release NuGet
    # if: github.event.pull_request.merged == true
    # environment: pr-nuget-release-workflow
    environment: no-secrets-workflow
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    # - uses: ncipollo/release-action@v1
    #   with:
    #     commit: ${{ github.event.pull_request.merge_commit_sha }}
    #     tag:
    #     artifacts: "release.tar.gz,foo/*.txt"
    #     # bodyFile: "body.md"
    #     token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Trigger NuGet publish workflow
    #   uses: peter-evans/repository-dispatch@v1.1.3
    #   with:
    #     token: ${{ secrets.REPOSITORY_DISPATCH_GH_TOKEN }}
    #     repository: ${{ github.repository}}
    #     event-type: release-nuget-pr-merged
