# When making changes to this file please update the corresponding documentation which can be found at /docs/dev-notes/workflows/pr-test-results-comment-workflow.md

name: PR test results comment

on:
  workflow_run:
    workflows: ["Publish Nuget packages"]
    types:
    - completed

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Add test results as PR comment
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - test-results-artifact-name: "test-results-ubuntu-latest"
           os: "ubuntu-latest"
         - test-results-artifact-name: "test-results-windows-latest"
           os: "windows-latest"
    env:
      TEST_RESULTS_ARTIFACT_NAME: ${{ matrix.test-results-artifact-name }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2.16.0
      continue-on-error: true
      with:
        workflow: nuget-publish.yml
        name:  ${{ env.TEST_RESULTS_ARTIFACT_NAME }}
        run_id: ${{ github.event.workflow_run.id }}
        path: ${{ env.TEST_RESULTS_ARTIFACT_NAME }}
    - name: Check artifact download
      id: artifact-download-check
      run: |
        if(Test-Path -Path ./${{ env.TEST_RESULTS_ARTIFACT_NAME }}){
          Write-Host "::set-output name=artifact-downloaded::true"
          Write-Host "Set output variable artifact-downloaded to true"
        }
        else{
          Write-Host "::set-output name=artifact-downloaded::false"
          Write-Host "Set output variable artifact-downloaded to false"
        }
    - name: Sanitize PR test results comment
      id: sanitize-pr-comment
      if: steps.artifact-download-check.outputs.artifact-downloaded == 'true'
      run: |
        $commentBody = "# [Test runs on ${{ matrix.os }}](${{ github.event.workflow_run.html_url }}) for commit ${{ github.event.workflow_run.head_sha }}`n`n"
        $commentBody += Get-Content ./${{ env.TEST_RESULTS_ARTIFACT_NAME }}/*.md -Raw # without the -Raw the escaping that happens next does not work. Not sure why.
        # The content must be escaped to preserve newlines. See https://github.community/t/set-output-truncates-multiline-strings/16852/3
        $commentBody = $commentBody -replace "`n","%0A"
        $commentBody = $commentBody -replace "`r","%0D"
        Write-Host "::set-output name=pr-comment-body::$commentBody"
    - name: Update PR with test results
      uses: ./.github/actions/create-update-comment
      if: steps.artifact-download-check.outputs.artifact-downloaded == 'true'
      with:
        issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
        body-includes: Test runs on ${{ matrix.os }}
        comment-author: github-actions[bot]
        body: ${{ steps.sanitize-pr-comment.outputs.pr-comment-body }}
        edit-mode: replace

