name: Test template renderers

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Test template renderers
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: chuhlomin/render-template
      id: chuhlomin-render-issue
      uses: chuhlomin/render-template@v1
      with:
        template: .github/workflows/templates/nuget-release-flow/nuget-released-successfully-issue-comment.md
        vars: |
          nugetId: 'nuget-id'
          nugetVersion: 'nuget-version'
          nugetUrl: 'https://www.nuget.org/packages/nuget-id'
          gitHubReleaseUrl: 'github-release-url'
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.chuhlomin-render-issue.outputs) }}
      run: $env:STEP_OUTPUT
    - name: Render template files
      uses: yukitsune/template-cli@v0.1.0
      with:
        args: --input .github/workflows/templates/nuget-release-flow/nuget-released-successfully-issue-comment.md \
          --value "nugetId=nuget-id" \
          --value "nugetVersion=nuget-version" \
          --value "nugetUrl=nuget-url" \
          --value "gitHubReleaseUrl=github-release" \
          --output .
    - name: Cat yukitsune output
      run: cat ./nuget-released-successfully-issue-comment.md
    - name: Set yukitsune output
      id: yukitsune
      run: |
        $fileOutput = Get-Content ./nuget-released-successfully-issue-comment.md
        $random = Get-Random
        $delimiter = "EOF_$random"
        Write-Output "my-var<<$delimiter" >> $env:GITHUB_OUTPUT
        Write-Output $fileOutput >> $env:GITHUB_OUTPUT
        Write-Output $delimiter >> $env:GITHUB_OUTPUT
    - name: Dump outputs from previous step
      env:
        STEP_OUTPUT: ${{ toJSON(steps.yukitsune.outputs) }}
      run: $env:STEP_OUTPUT
    - name: Dump outputs from previous step 2
      run: Write-Output ${{ steps.yukitsune.outputs.my-var }}
